[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.isort]
profile = "black"
known_third_party = ["PIL", "fire", "loguru", "matplotlib", "mlflow", "mmcls", "mmcv", "numpy", "pandas", "plotly", "pydantic", "pytest", "seaborn", "sklearn", "torch"]
