name: ai-project-cifar10
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pytorch=1.9
  - torchvision=0.10.0
  - pip=21.1.3
  - cruft=2.9.0
  - dvc=2.5.4
  - fire=0.4.0
  - loguru=0.5.3
  - pydantic=1.8.2
  - pre-commit=2.13.0
  - mlflow=1.19.0
  - pytest=6.2.4
  - scikit-learn=0.24.2
  - seaborn=0.11.0
  - plotly=5.1.0
  - cookiecutter=1.7.3
  - pip:
    - opencv-contrib-python
    - torch-model-archiver==0.4.1
    - mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
    - mmcls==0.13.0
